[package]
name = "pqgram-pybindings"
version = "0.1.0"
authors = ["Cathal Garvey <cathalgarvey@cathalgarvey.me>"]

[lib]
name = "pqgrams"
crate-type = ["cdylib"]

[dependencies]
pqgrams = "0.9.2"
itertools = "0.6"

[dependencies.cpython]
version = "0.1"
default-features = true
